### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by luca-della-vedova** [berkeleyopenarms/bldc-controller#11]
Hi guys,

Might be worth it to discuss and choose the License for this project, especially for people who are interested in customizing the controller for their own application?

Cheers!
/Luca

**Comment by brentyi** [comment]
Yes, this is a good idea, and not just limited to the motor controller code.

(we can discuss this internally, but tagging @wuphilipp @gbalke @allanzhao for thoughts)

**Comment by brentyi** [comment]
We decided on MIT for everything -- thanks for bringing this up Luca!
